"use client";

import type { Metadata } from 'next'
import { Inter, Alef } from 'next/font/google'
import './globals.css'
import { cn } from '@/lib/utils'
import {Advert, Navbar, Footer} from '@/other-components'
import { ThemeProvider } from '@/components/ThemeProvider'
import { Toaster } from '@/components/ui/toaster'
import { Provider } from 'react-redux'
import { Store, persistor } from '../redux/store'
import { PersistGate } from 'redux-persist/integration/react';

const alef = Alef({ subsets:['latin'], weight: "400", style: "normal", fallback: ['Monospace', 'helvetica'] })
// const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn("relative h-full antialiased dark:bg-[#1A1C29]", alef.className)}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <Provider store={Store}>
            <PersistGate persistor={persistor}>
              <Advert />
              <Navbar />
              <main>{children}</main>
              <Footer />
            </PersistGate>
          </Provider>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  )
}
