import type { Metadata } from 'next'
import { Inter, Alef } from 'next/font/google'
import './globals.css'
import { cn } from '@/lib/utils'
import {Advert, Navbar} from '@/other-components'
import { ThemeProvider } from '@/components/ThemeProvider'


const alef = Alef({ subsets:['latin'], weight: "400", style: "normal", fallback: ['Monospace', 'helvetica'] })
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn("relative h-full antialiased dark:bg-[#1A1C29]", alef.className)}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <Advert />
          <Navbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
